### PR TITLE
Update to Mozjpeg 3

### PR DESCRIPTION
**Pull request by kornelski**

### CODE REVIEW

**Comment by bdaehlie** [comment]
Thanks @pornel. It looks like you changed some of the metric target float values though, can you explain? I'd like to leave them the same for consistency with out last study.

**Comment by kornelski** [comment]
I've copied the values from cjpeg

**Comment by kornelski** [comment]
I've removed the commit that changed the values

**Comment by bdaehlie** [comment]
In 3 out of 4 cases the original line is this:

cinfo.use_flat_quant_tbl = TRUE;

In 2 of those cases you translate it to this:

jpeg_c_set_int_param(&cinfo, JINT_BASE_QUANT_TBL_IDX, 1);

In the third case you translate it to:

jpeg_c_set_int_param(&cinfo, JINT_BASE_QUANT_TBL_IDX, 3);

Which is what you did for when:

cinfo.use_flat_quant_tbl = FALSE;

It seems like a mistake in the third case, no?

**Comment by bdaehlie** [comment]
I'm going to merge this and direct push a fix for the issue I pointed out above.

**Comment by kornelski** [comment]
It was supposed to be:

`use_flat_quant_tbl = TRUE;` = `JINT_BASE_QUANT_TBL_IDX, 1);`

`use_flat_quant_tbl = FALSE;` = `JINT_BASE_QUANT_TBL_IDX, 3);`

I've copied these from `cjpeg.c` in mozjpeg.

**Pull request merged**
